# Generated by Django 3.0.8 on 2020-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottey_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_price_code', models.CharField(max_length=2)),
                ('first_price_number', models.CharField(max_length=6)),
            ],
        ),
    ]
