# Generated by Django 3.0.8 on 2020-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockistship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('agency_name', models.CharField(max_length=20)),
                ('contact_number1', models.CharField(max_length=10)),
                ('contact_number2', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
