# Generated by Django 3.0.8 on 2020-09-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0002_stockistship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stockistship',
        ),
    ]
