# Generated by Django 3.0.8 on 2020-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0003_delete_stockistship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottey_result',
            name='first_price_code',
        ),
        migrations.RemoveField(
            model_name='lottey_result',
            name='first_price_number',
        ),
        migrations.AddField(
            model_name='lottey_result',
            name='fifth_price',
            field=models.CharField(default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='lottey_result',
            name='first_price',
            field=models.CharField(default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='lottey_result',
            name='fourth_price',
            field=models.CharField(default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='lottey_result',
            name='sixth_price',
            field=models.CharField(default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='lottey_result',
            name='third_price',
            field=models.CharField(default='123', max_length=3),
        ),
    ]
