# Generated by Django 3.0.8 on 2020-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0004_auto_20200908_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottey_result',
            name='fifth_price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='first_price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='fourth_price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='sixth_price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='third_price',
            field=models.CharField(max_length=3),
        ),
    ]
