# Generated by Django 3.0.8 on 2020-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0006_lottey_result_second_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottey_result',
            name='second_price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='sixth_price',
            field=models.TextField(max_length=200),
        ),
    ]
