# Generated by Django 3.0.8 on 2020-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0008_auto_20200909_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottey_result',
            options={},
        ),
        migrations.AlterField(
            model_name='lottey_result',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
