# Generated by Django 3.0.8 on 2020-09-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0010_auto_20200910_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottey_result',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
