# Generated by Django 3.0.8 on 2020-09-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0011_auto_20200910_0653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lottey_Result',
            new_name='Lottey_Result_2PM',
        ),
    ]
