# Generated by Django 3.0.8 on 2020-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0016_auto_20200913_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockist_model',
            name='existing_stocklist_status',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='stockist_model',
            name='stockist_type',
            field=models.CharField(choices=[('S', 'STOCKIST'), ('SS', 'SUB-STOCKIST'), ('SE', 'SELLER')], default='SUB-STOCKIST', max_length=2),
        ),
    ]
