# Generated by Django 3.0.8 on 2020-09-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0017_auto_20200913_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='contact_number',
            new_name='last_name',
        ),
    ]
