# Generated by Django 3.0.8 on 2020-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0018_auto_20200913_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockist_model',
            old_name='mobile_number_1',
            new_name='contact_number_1',
        ),
        migrations.RenameField(
            model_name='stockist_model',
            old_name='mobile_number_2',
            new_name='contact_number_2',
        ),
        migrations.AlterField(
            model_name='stockist_model',
            name='existing_stocklist_status',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='stockist_model',
            name='stockist_type',
            field=models.CharField(choices=[('S', 'STOCKIST'), ('SS', 'SUB-STOCKIST'), ('SE', 'SELLER')], max_length=2),
        ),
    ]
