# Generated by Django 3.0.8 on 2020-09-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0019_auto_20200913_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
