# Generated by Django 3.0.8 on 2020-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyapp', '0021_date_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottey_result_2pm',
            name='fifth_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_2pm',
            name='fourth_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_2pm',
            name='second_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_2pm',
            name='sixth_price',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='lottey_result_2pm',
            name='third_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='fifth_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='first_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='fourth_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='second_price',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='sixth_price',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='lottey_result_5pm',
            name='third_price',
            field=models.CharField(max_length=70),
        ),
    ]
